# Generated by Django 4.1 on 2023-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FriTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friday_mon", models.CharField(max_length=263)),
                ("friday_aft", models.CharField(max_length=263)),
                ("friday_even", models.CharField(max_length=263)),
            ],
        ),
        migrations.CreateModel(
            name="MonTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday_mon", models.CharField(max_length=263)),
                ("monday_aft", models.CharField(max_length=263)),
                ("monday_even", models.CharField(max_length=263)),
            ],
        ),
        migrations.CreateModel(
            name="SatTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saturday_mon", models.CharField(max_length=263)),
                ("saturday_aft", models.CharField(max_length=263)),
                ("saturday_even", models.CharField(max_length=263)),
            ],
        ),
        migrations.CreateModel(
            name="SunTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sunday_mon", models.CharField(max_length=263)),
                ("sunday_aft", models.CharField(max_length=263)),
                ("sunday_even", models.CharField(max_length=263)),
            ],
        ),
        migrations.CreateModel(
            name="ThuTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thursday_mon", models.CharField(max_length=263)),
                ("thursday_aft", models.CharField(max_length=263)),
                ("thursday_even", models.CharField(max_length=263)),
            ],
        ),
        migrations.CreateModel(
            name="TueTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuesday_mon", models.CharField(max_length=263)),
                ("tuesday_aft", models.CharField(max_length=263)),
                ("tuesday_even", models.CharField(max_length=263)),
            ],
        ),
        migrations.CreateModel(
            name="WedTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wednesday_mon", models.CharField(max_length=263)),
                ("wednesday_aft", models.CharField(max_length=263)),
                ("wednesday_even", models.CharField(max_length=263)),
            ],
        ),
    ]
