# Generated by Django 4.1 on 2023-08-08 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesheet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FriTimesheet",
        ),
        migrations.DeleteModel(
            name="MonTimesheet",
        ),
        migrations.DeleteModel(
            name="SatTimesheet",
        ),
        migrations.DeleteModel(
            name="SunTimesheet",
        ),
        migrations.DeleteModel(
            name="ThuTimesheet",
        ),
        migrations.DeleteModel(
            name="TueTimesheet",
        ),
        migrations.DeleteModel(
            name="WedTimesheet",
        ),
    ]
