# Generated by Django 4.1 on 2023-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesheet",
            "0003_loan_personal_info_timesheetentry_userprofileinfo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="day_time",
            field=models.CharField(
                choices=[
                    ("Morning", "Morning"),
                    ("Afternoon", "Afternoon"),
                    ("Evening", "Evening"),
                ],
                default="Morning",
                max_length=10,
            ),
        ),
    ]
